server:
    port: 8081
    servlet:
        session:
            tracking-modes: cookie

logging:
    level:
        org:
            apache:
                coyote:
                    http11: debug

spring:
    messages:
        basename: messages,errors