server:
    port: 8081
    servlet:
        session:
            tracking-modes: cookie
    error:
        whitelabel:
            enabled: true
        path: /error
        include-exception: true
        include-message: on_param
        include-stacktrace: on_param
        include-binding-errors: on_param

logging:
    level:
        org:
            apache:
                coyote:
                    http11: debug

spring:
    messages:
        basename: messages,errors