server:
    port: 8081
    servlet:
        session:
            tracking-modes: cookie
        multipart:
            max-file-size: 1MB
            max-request-size: 10MB
    error:
        whitelabel:
            enabled: true
        path: /error
        include-exception: true
        include-message: always
        include-stacktrace: always
        include-binding-errors: always

logging:
    level:
        org:
            apache:
                coyote:
                    http11: debug

spring:
    messages:
        basename: messages,errors